SOURCES = \
	stringUtil.ml \
	lambdaman.ml  lambdamanReader.ml \
	ghost.ml ghostAiParser.mly ghostAiLexer.mll ghostAiReader.ml \
	fieldReader.ml \
	simulator.ml
RESULT  = simulator

all: native-code

OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)
